server:
  port: 8088

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2-server?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: false
    show-sql: true
app:
  security:
    client-id: emr-client-id
    client-secret: MJx7vPwDPe7E9k6yeDB4
    grant-type: password, authorization_code, refresh_token, client_credentials
    scopes: read, write
    access-token-expire-time: 5000
    refresh-token-expire-time: 50000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
